<?php

function title_case_menu() {
    $items = array();
    $items['title_case'] = array(
        'title' => 'Title Case Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['title_case_success_page'] = array(
        'title' => 'Here is your titlecased message',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['title_cased'] = array(
        '#title' => 'Title Case',
        '#type' => 'textfield',
        '#description' => t('Please enter a message to have it title cased.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {

    $input_title = $form_state['values']['title_cased'];
    $output_titlecased = array();


    //Preposition and conjunction array
    $prep_con = array("a","an","and","as","at","but","by",
    "en","for","if","in","of","on","or","the","to", "from");
    //prefixes to check for
    $prefix = array("mc", "o'");
    //Seperates string by space and stores into an array
    $input_array_of_words = explode(" ", strtolower($input_title));
    //Grab first index
    $first_word = ucfirst(array_shift($input_array_of_words));
    //Storage array
    $output_titlecased = array();
    //Caps the first letter of all words
    foreach($input_array_of_words as $word) {
        //Checks to see if the input is a conjuction or prep
        /// if it is then we make sure to not capitalize it.
        if(in_array($word, $prep_con)){
            array_push($output_titlecased, $word);
        //Prefix fix
        }elseif(in_array(substr($word, 0, 2), $prefix)){
            $storage = str_split($word);
            $storage[2] = strtoupper($storage[2]);
            $storage = implode("", $storage);
            array_push($output_titlecased, ucfirst($storage));
        }else{
            array_push($output_titlecased, ucfirst($word));
        }
    }
    array_unshift($output_titlecased, $first_word);
    $titlecased_string = implode(" ", $output_titlecased);

    $_SESSION['title_case_output'] = $titlecased_string;
    $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  return $_SESSION['title_case_output'];
}
